name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_1 (Prueba 1)
      id: test_1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_1 (Prueba 1)
        setup-command: pip install pytest
        command: pytest tests/test_1.py
        timeout: 10
        max-score: 10
      # Verifica la salida del paso anterior para personalizar el feedback
      run: |
        if [[ ${{ steps.test_1.outputs.result }} == "success" ]]; then
          echo "**¡Enhorabuena! La prueba 1 se ejecutó correctamente.**"
        else
          echo "**Falló la prueba 1.** Revisa el error: ${{ steps.test_1.outputs.error }}"
        fi
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_1_RESULTS: "${{ steps.test_1.outputs.result }}"
      with:
        runners: test_1